using Application;
using AutoFixture;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace CalculatorTest
{
    public class AutoFixtureAnonymousDataExample
    {
        [Fact]
        [Trait("Category", "AutoFixture")]
        public void TestWithHandCreatedString()
        {
            var inputString = "hello";

            var result = inputString.ToUpper();

            Assert.Equal("HELLO", result);
        }

        [Fact]
        [Trait("Category", "AutoFixture")]
        public void TestWithAutogeneratedString()
        {
            var fixture = new Fixture();
            var inputString = fixture.Create<string>();

            var sut = new StringUtils();

            var result = sut.MakeUpper(inputString);

            Assert.Equal(inputString.ToUpper(), result);
        }
    }
}
